<div class="admin-page-head"><div><a href="{{ route('admin.faculty-log-books.index') }}" class="admin-back-link">{{ trans('global.back_to_list') }}</a><h2 class="admin-page-title">{{ $facultyLogBook ? 'Edit Faculty Log' : 'Add Faculty Log' }}</h2></div></div>
<form method="POST" action="{{ $action }}">@csrf @if($method !== 'POST') @method($method) @endif
<div class="admin-form-grid"><div class="form-card" style="grid-column:1/-1;"><div class="form-card-body">
<div class="field-group"><label class="field-label">Teacher</label><select name="teacher_id" class="field-input" required>@foreach($teachers as $id=>$name)<option value="{{ $id }}" {{ old('teacher_id', $facultyLogBook->teacher_id ?? '') == $id ? 'selected' : '' }}>{{ $name }}</option>@endforeach</select></div>
<div class="field-group"><label class="field-label">Batch</label><select name="batch_id" class="field-input">@foreach($batches as $id=>$name)<option value="{{ $id }}" {{ old('batch_id', $facultyLogBook->batch_id ?? '') == $id ? 'selected' : '' }}>{{ $name }}</option>@endforeach</select></div>
<div class="field-group"><label class="field-label">Subject</label><select name="subject_id" class="field-input">@foreach($subjects as $id=>$name)<option value="{{ $id }}" {{ old('subject_id', $facultyLogBook->subject_id ?? '') == $id ? 'selected' : '' }}>{{ $name }}</option>@endforeach</select></div>
<div class="field-group"><label class="field-label">Lecture Date</label><input type="date" name="lecture_date" class="field-input" required value="{{ old('lecture_date', isset($facultyLogBook) && $facultyLogBook->lecture_date ? $facultyLogBook->lecture_date->format('Y-m-d') : date('Y-m-d')) }}"></div>
<div class="field-group"><label class="field-label">Scheduled Start</label><input type="time" name="scheduled_start_time" class="field-input" required value="{{ old('scheduled_start_time', $facultyLogBook->scheduled_start_time ?? '') }}"></div>
<div class="field-group"><label class="field-label">Scheduled End</label><input type="time" name="scheduled_end_time" class="field-input" required value="{{ old('scheduled_end_time', $facultyLogBook->scheduled_end_time ?? '') }}"></div>
<div class="field-group"><label class="field-label">Actual Start</label><input type="time" name="actual_start_time" class="field-input" value="{{ old('actual_start_time', $facultyLogBook->actual_start_time ?? '') }}"></div>
<div class="field-group"><label class="field-label">Actual End</label><input type="time" name="actual_end_time" class="field-input" value="{{ old('actual_end_time', $facultyLogBook->actual_end_time ?? '') }}"></div>
<div class="field-group"><label class="field-label">Topic Taught</label><input name="topic_taught" class="field-input" value="{{ old('topic_taught', $facultyLogBook->topic_taught ?? '') }}"></div>
<div class="field-group"><label class="field-label">Log Status</label><select name="log_status" class="field-input"><option value="submitted" {{ old('log_status', $facultyLogBook->log_status ?? 'submitted') === 'submitted' ? 'selected' : '' }}>Submitted</option><option value="draft">Draft</option><option value="missed">Missed</option><option value="late_entry">Late Entry</option></select></div>
<div class="field-group"><label class="field-label">Approval Status</label><select name="approval_status" class="field-input"><option value="pending" {{ old('approval_status', $facultyLogBook->approval_status ?? 'pending') === 'pending' ? 'selected' : '' }}>Pending</option><option value="approved" {{ old('approval_status', $facultyLogBook->approval_status ?? '') === 'approved' ? 'selected' : '' }}>Approved</option><option value="rejected" {{ old('approval_status', $facultyLogBook->approval_status ?? '') === 'rejected' ? 'selected' : '' }}>Rejected</option></select></div>
<div class="field-group"><label class="field-label">Remarks</label><textarea name="remarks" class="field-input">{{ old('remarks', $facultyLogBook->remarks ?? '') }}</textarea></div>
</div></div></div><div class="form-actions"><button class="btn-primary"><i class="fas fa-check"></i> {{ trans('global.save') }}</button></div></form>
