<div class="admin-page-head"><div><a href="{{ route('admin.student-batches.index') }}" class="admin-back-link">{{ trans('global.back_to_list') }}</a><h2 class="admin-page-title">{{ $studentBatch ? 'Edit Student Batch' : 'Assign Student Batch' }}</h2></div></div>
<form method="POST" action="{{ $action }}">@csrf @if($method !== 'POST') @method($method) @endif
<div class="admin-form-grid"><div class="form-card" style="grid-column:1/-1;"><div class="form-card-body">
<div class="field-group"><label class="field-label">Student</label><select name="student_id" class="field-input" required>@foreach($students as $id=>$name)<option value="{{ $id }}" {{ old('student_id', $studentBatch->student_id ?? '') == $id ? 'selected' : '' }}>{{ $name }}</option>@endforeach</select></div>
<div class="field-group"><label class="field-label">Batch</label><select name="batch_id" class="field-input" required>@foreach($batches as $id=>$name)<option value="{{ $id }}" {{ old('batch_id', $studentBatch->batch_id ?? '') == $id ? 'selected' : '' }}>{{ $name }}</option>@endforeach</select></div>
<div class="field-group"><label class="field-label">Subject</label><select name="subject_id" class="field-input">@foreach($subjects as $id=>$name)<option value="{{ $id }}" {{ old('subject_id', $studentBatch->subject_id ?? '') == $id ? 'selected' : '' }}>{{ $name }}</option>@endforeach</select></div>
<div class="field-group"><label class="field-label">Start Date</label><input type="date" name="start_date" class="field-input" value="{{ old('start_date', isset($studentBatch) && $studentBatch->start_date ? $studentBatch->start_date->format('Y-m-d') : '') }}"></div>
<div class="field-group"><label class="field-label">End Date</label><input type="date" name="end_date" class="field-input" value="{{ old('end_date', isset($studentBatch) && $studentBatch->end_date ? $studentBatch->end_date->format('Y-m-d') : '') }}"></div>
<div class="field-group"><label class="field-label">Status</label><select name="status" class="field-input"><option value="active" {{ old('status', $studentBatch->status ?? 'active') === 'active' ? 'selected' : '' }}>Active</option><option value="inactive" {{ old('status', $studentBatch->status ?? '') === 'inactive' ? 'selected' : '' }}>Inactive</option></select></div>
</div></div></div><div class="form-actions"><button class="btn-primary"><i class="fas fa-check"></i> {{ trans('global.save') }}</button></div></form>
