<div class="admin-page-head"><div><a href="{{ route('admin.extra-classes.index') }}" class="admin-back-link">{{ trans('global.back_to_list') }}</a><h2 class="admin-page-title">{{ $extraClass ? 'Edit Extra Class' : 'Add Extra Class' }}</h2></div></div>
<form method="POST" action="{{ $action }}">@csrf @if($method !== 'POST') @method($method) @endif
<div class="admin-form-grid"><div class="form-card" style="grid-column:1/-1;"><div class="form-card-body">
<div class="field-group"><label class="field-label">Teacher</label><select name="teacher_id" class="field-input" required>@foreach($teachers as $id=>$name)<option value="{{ $id }}" {{ old('teacher_id', $extraClass->teacher_id ?? '') == $id ? 'selected' : '' }}>{{ $name }}</option>@endforeach</select></div>
<div class="field-group"><label class="field-label">Batch</label><select name="batch_id" class="field-input">@foreach($batches as $id=>$name)<option value="{{ $id }}" {{ old('batch_id', $extraClass->batch_id ?? '') == $id ? 'selected' : '' }}>{{ $name }}</option>@endforeach</select></div>
<div class="field-group"><label class="field-label">Subject</label><select name="subject_id" class="field-input">@foreach($subjects as $id=>$name)<option value="{{ $id }}" {{ old('subject_id', $extraClass->subject_id ?? '') == $id ? 'selected' : '' }}>{{ $name }}</option>@endforeach</select></div>
<div class="field-group"><label class="field-label">Class Date</label><input type="date" name="class_date" class="field-input" required value="{{ old('class_date', isset($extraClass) && $extraClass->class_date ? $extraClass->class_date->format('Y-m-d') : date('Y-m-d')) }}"></div>
<div class="field-group"><label class="field-label">Start Time</label><input type="time" name="start_time" class="field-input" required value="{{ old('start_time', $extraClass->start_time ?? '') }}"></div>
<div class="field-group"><label class="field-label">End Time</label><input type="time" name="end_time" class="field-input" required value="{{ old('end_time', $extraClass->end_time ?? '') }}"></div>
<div class="field-group"><label class="field-label">Approval Status</label><select name="approval_status" class="field-input"><option value="pending" {{ old('approval_status', $extraClass->approval_status ?? 'pending') === 'pending' ? 'selected' : '' }}>Pending</option><option value="approved" {{ old('approval_status', $extraClass->approval_status ?? '') === 'approved' ? 'selected' : '' }}>Approved</option><option value="rejected" {{ old('approval_status', $extraClass->approval_status ?? '') === 'rejected' ? 'selected' : '' }}>Rejected</option></select></div>
<div class="field-group"><label class="field-label">Salary Amount</label><input type="number" step="0.01" name="salary_amount" class="field-input" value="{{ old('salary_amount', $extraClass->salary_amount ?? 0) }}"></div>
<div class="field-group"><label class="field-label">Reason</label><textarea name="reason" class="field-input">{{ old('reason', $extraClass->reason ?? '') }}</textarea></div>
<div class="field-group"><label class="field-label">Remarks</label><textarea name="remarks" class="field-input">{{ old('remarks', $extraClass->remarks ?? '') }}</textarea></div>
</div></div></div><div class="form-actions"><button class="btn-primary"><i class="fas fa-check"></i> {{ trans('global.save') }}</button></div></form>
