@extends('layouts.admin')
@section('page-title', 'Extra Classes')
@section('content')
<div class="admin-page-head"><div><h2 class="admin-page-title">Extra Classes</h2><p class="admin-page-subtitle">Only approved extra classes count for salary</p></div>@can('extra_class_create')<a href="{{ route('admin.extra-classes.create') }}" class="btn-primary"><i class="fas fa-plus"></i> Add Extra Class</a>@endcan</div>
<div class="page-card"><div class="page-card-table"><table class="min-w-full datatable datatable-ExtraClasses"><thead><tr><th>Date</th><th>Teacher</th><th>Batch</th><th>Time</th><th>Minutes</th><th>Amount</th><th>Status</th><th style="text-align:right;">Actions</th></tr></thead><tbody>
@foreach($extraClasses as $extraClass)<tr><td>{{ $extraClass->class_date ? $extraClass->class_date->format('d M Y') : '-' }}</td><td>{{ $extraClass->teacher->user->name ?? '-' }}</td><td>{{ $extraClass->batch->name ?? '-' }}</td><td>{{ $extraClass->start_time }} - {{ $extraClass->end_time }}</td><td>{{ $extraClass->approval_status === 'approved' ? $extraClass->salary_minutes : 0 }}</td><td>{{ number_format($extraClass->salary_amount, 2) }}</td><td><span class="status-pill {{ $extraClass->approval_status === 'approved' ? 'success' : ($extraClass->approval_status === 'rejected' ? 'danger' : 'warning') }}">{{ ucfirst($extraClass->approval_status) }}</span></td><td style="text-align:right;"><div class="action-row">@can('extra_class_edit')<a class="btn-outline btn-outline-edit" href="{{ route('admin.extra-classes.edit', $extraClass->id) }}"><i class="fas fa-pencil-alt"></i> Edit</a>@endcan @can('extra_class_approve')<form method="POST" action="{{ route('admin.extra-classes.approve', $extraClass->id) }}" style="display:inline">@csrf<button class="btn-outline"><i class="fas fa-check"></i> Approve</button></form><form method="POST" action="{{ route('admin.extra-classes.reject', $extraClass->id) }}" style="display:inline">@csrf<button class="btn-outline btn-outline-danger"><i class="fas fa-times"></i> Reject</button></form>@endcan</div></td></tr>@endforeach
</tbody></table></div></div>
@endsection
@section('scripts')@parent<script>$(function(){initAdminDataTable('.datatable-ExtraClasses',{searchPlaceholder:'Search extra classes...'});});</script>@endsection
